# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sonar Cloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # Get checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #  Replace Sonar Project Version
      - name: Replace Sonar Project Version
        shell: bash
        run: |
          sed -i -e 's/$APP_VERSION/latest/g' "./sonar-project.properties"

      # Run Sonar Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master # cspell:ignore sonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
